on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
        go:
          - '1.11'
          - '1.12'
          - '1.13'
          - '1.14'
          - '1.15'
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: make
      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: goformat-${{ matrix.os }}-${{ matrix.go }}
          path: bin/
